# Generated by Django 3.0.8 on 2020-08-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.IntegerField(default=1111, max_length=5),
            preserve_default=False,
        ),
    ]
