# Generated by Django 3.0.8 on 2020-08-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_employee_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='gsheet_id',
            field=models.CharField(default='test', max_length=80),
            preserve_default=False,
        ),
    ]
