# Generated by Django 3.0.8 on 2020-09-12 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_attandance_gsheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attandance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
