# Generated by Django 3.0.8 on 2020-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_auto_20200912_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
