# Generated by Django 3.0.8 on 2020-07-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('temperatur', models.FloatField(blank=True, null=True)),
                ('mixTimeOne', models.CharField(blank=True, max_length=150, null=True)),
                ('mixTimeTwo', models.CharField(blank=True, max_length=150, null=True)),
                ('rest', models.DurationField(blank=True, null=True)),
                ('charge_amount', models.IntegerField(blank=True, null=True)),
                ('charge_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Measurement')),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('temperatur', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='production.Recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Measurement')),
            ],
            options={
                'ordering': ['ingredient'],
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('checked', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('product_list_id', models.CharField(blank=True, max_length=300, null=True)),
                ('orders', models.ManyToManyField(to='production.Orders')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Recipe')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Measurement'),
        ),
        migrations.CreateModel(
            name='IngredientSupplierItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_until', models.DateTimeField()),
                ('Ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Ingredient')),
                ('supplier_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.SupplierItems')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('checked', models.BooleanField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Ingredient')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Production')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Measurement')),
            ],
            options={
                'unique_together': {('production', 'ingredient')},
            },
        ),
    ]
