# Generated by Django 3.0.8 on 2020-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='date',
            new_name='bake_date',
        ),
        migrations.AddField(
            model_name='production',
            name='mix_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
