# Generated by Django 3.0.8 on 2020-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20200801_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='actual_temperatur',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10),
            preserve_default=False,
        ),
    ]
