# Generated by Django 3.0.8 on 2020-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20200803_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='charge_amount',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=15),
            preserve_default=False,
        ),
    ]
