# Generated by Django 3.0.8 on 2020-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200803_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='actual_temperatur',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
