# Generated by Django 3.0.8 on 2020-08-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20200804_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='actual_temperatur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
