# Generated by Django 3.0.8 on 2020-08-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20200804_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='actual_temperatur',
        ),
    ]
