# Generated by Django 3.0.8 on 2020-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_production_actual_temperatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='actual_temperatur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
