# Generated by Django 3.0.8 on 2020-08-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_production_actual_temperatur'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sensor_id', models.CharField(max_length=100)),
            ],
        ),
    ]
