# Generated by Django 3.0.8 on 2020-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_temperatursensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatursensor',
            name='humidity',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
