# Generated by Django 3.0.8 on 2020-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20200806_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatursensor',
            name='humidity',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
